[HITBTC]
public_key = ""
secret = ""

[KUCOIN]
public_key = ""
secret = ""

[CRYPTOPIA]
public_key = ""
secret = ""

[BITTREX]
public_key = ""
secret = ""

[BINANCE]
public_key = ""
secret = ""

[KRAKEN]
public_key = ""
secret = ""
