version: '2'
services:
    monitorapp2:
        build:
            context: ./
            dockerfile: docker_monitor
        #container_name: "monitorapp"
        #image: debian/latest
        environment:
            - NODE_ENV=development
            - MONGODB_PORT_27017_TCP_ADDR
            - FOO=bar
        volumes:
            #- ./dockerimg:/root/log
            - /tmp:/tmp
        ports:
            - 3000:3000
            - 9000:9000
        links:
            - mongodb
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - /tmp/data/db:/data/db
        ports:
            - 27017:27017
        #command: mongod --smallfiles --logpath=/dev/null # --quiet
        ##docker run -d -v /tmp/tommy.py:/opt/tommy.py python:3.5 python /opt/tommy.py